# Jekyll-config for Viriditas site

# Site Metadata
title: Viriditas
description: Engineering Biology for Space Exploration: 10/20/2018 Boston, MA.

# Speaker and organizer data are collections, rather than
# individual summaries
collections:
  speakers:
  about:

# Jekyll Settings
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
timezone: America/New_York
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jemoji

