# Jekyll-config for Viriditas site

# Site Metadata
title: Viriditas
description: Engineering Biology for Space Exploration

# Speaker and organizer data are collections, rather than
# individual summaries
collections:
  sections:
  speakers:
  keynote:
  organizers:

# Jekyll Settings
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - vendor
timezone: America/New_York
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-debug
