# Jekyll-config for Viriditas site

# Site Metadata
title: Viriditas
description: Engineering Biology for Space Exploration  

# Speaker data as its own collection
collections:
  speakers:
  
collections:
  about:

# Jekyll Settings
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
timezone: America/New_York
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jemoji

